name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9
    - name: Publish
      run: |
        dotnet publish -c Release /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.Sha }}
        mkdir artifacts
        tar -czvf artifacts/mickey.tar.gz Mickey/bin/Release/net7.0/linux-arm64/publish/
        tar -czvf artifacts/goofy.tar.gz Goofy/bin/Release/net7.0/linux-arm64/publish/
        tar -czvf artifacts/servoTest.tar.gz ServoTest/bin/Release/net7.0/linux-arm64/publish/
    - run: gh release create ${{ steps.gitversion.outputs.semVer }} artifacts/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      name: Create GitHub release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: publish-output
        path: artifacts/*.tar.gz 
